### PR TITLE
fix(load): updated queue utils

### LINKED ISSUE #10: Improve the typing of the extension-load-queue
The `src/lib/extension-load-queue.ts` describes the mechanism for asynchronous loading of executable scripts using packages. This process is achieved through a queue and by adding a field to the window object. Symbol data types are used to protect against external interference. This mechanism is employed in such extensions as mermaid, LaTeX, and HTML.

The file is described using TypeScript. At the same time, it contains a number of areas that could be improved.

### Suggestion for improvement
1. fix TODO
2. add docs
3. move the isBrowser function

### PR DESCRIPTION
**Pull request by makhnatkin**

### CODE REVIEW

**Review by 3y3 — APPROVED** [review]

File: src/lib/extension-load-queue.ts [hunk 1]
```diff
@@ -1,63 +1,149 @@
...
+    // The store where callbacks are saved
     store: ScriptStore<T>;
+
+    // Function that creates a controller
     createController: () => T;
+
+    // Flag to check if the queue is already created
     isQueueCreated?: boolean;
+
+    // Callback to handle queue creation
```
Comment (brotheroftux) [inline src/lib/extension-load-queue.ts]: Interface members should be annotated with JSDoc-styled comments as well `/** */`

File: src/lib/extension-load-queue.ts [hunk 2]
```diff
@@ -1,63 +1,149 @@
...
+ * Retrieves or initializes a script store for the given symbol key.
+ *
+ * @param {symbol} storeKey - The key associated with the script store.
+ * @returns {ScriptStore<T>} The script store associated with the given key.
+ */
+export const getScriptStore = <T>(storeKey: symbol): ScriptStore<T> => {
     if (isBrowser()) {
-        (window as Window)[key] = (window as Window)[key] || [];
-        return (window as Window)[key];
+        // Initialize the store if it does not exist or check that it is an array
```
Comment (brotheroftux) [inline src/lib/extension-load-queue.ts:86]: In my opinion, this commenting style is too verbose. JSDoc is fine, but I don't think we really need to comment on every other statement.

File: src/lib/extension-load-queue.ts [hunk 3]
```diff
@@ -1,63 +1,149 @@
...
+ */
+const ensureQueuesSymbolInitialized = (): void => {
     if (isBrowser()) {
-        (window as Window)[QUEUE_SYMBOL] = (window as Window)[QUEUE_SYMBOL] || false;
-        return (window as Window)[QUEUE_SYMBOL];
+        if (typeof window[QUEUES_SYMBOL] !== 'object' || window[QUEUES_SYMBOL] === null) {
+            window[QUEUES_SYMBOL] = {};
+        }
+    } else {
+        throw new Error('This functionality should be employed on the client-side.');
```
Comment (brotheroftux) [inline src/lib/extension-load-queue.ts]: I don't think this error message is self-descriptive enough. The message should mention that it comes from a load queue. Maybe something along the lines of `Cannot initialize QueueStore in a non-browser environment`?

File: src/lib/extension-load-queue.ts [hunk 4]
```diff
@@ -81,27 +169,44 @@ export const createLoadQueue = <T>({
...
             return () => {
                 const index = store.indexOf(setController);
                 if (index > -1) {
+                    // Remove setController when unmounting
                     store.splice(index, 1);
                 }
             };
+        } else {
+            // eslint-disable-next-line no-console
+            console.warn('Store is not provided to useController'); // Replace console.warn with a logging function if necessary
```
Comment (brotheroftux) [inline src/lib/extension-load-queue.ts]: I'd say just throwing makes more sense here, maybe even removing the `if (store)` check altogether, since `store` cannot be nullable judging from the argument types

File: src/lib/index.ts [hunk 5]
```diff
@@ -3,20 +3,20 @@ import {
...
 } from './extension-load-queue';
+import {isBrowser} from './browser';
 
 export {
     AttrsParser,
     createLoadQueue,
     getQueueStore,
     getScriptStore,
-    handleQueueCreated,
+    createHandleQueueCreated,
```
Comment (brotheroftux) [inline src/lib/index.ts]: Do we really need to export this? This seems like an internal handler.

File: src/lib/extension-load-queue.ts [hunk 6]
```diff
@@ -1,63 +1,149 @@
...
+ */
 export const createLoadQueue = <T>({
     store,
     createController,
-    isQueueCreated = getQueueStore(),
-    onQueueCreated = handleQueueCreated,
-}: CreateLoadQueueArgs<T>) => {
+    queueKey = SINGLE_QUEUE_SYMBOL,
+    isQueueCreated = getQueueStore(queueKey),
+    onQueueCreated = createHandleQueueCreated(queueKey),
```
Comment (brotheroftux) [inline src/lib/extension-load-queue.ts:150]: I can't say I like the fact we can pass in custom `onQueueCreated`, which would effectively break the whole system — the default handler does a very important job of tracking which queues were initialized. So my guess is we don't want to expose this option to the end user.

**Review by brotheroftux — CHANGES_REQUESTED** [review]

File: src/lib/extension-load-queue.ts (hunk 6 above)
Comment (makhnatkin) [reply src/lib/extension-load-queue.ts:150]: I did not want to associate the `createLoadQueue` with the `window` runtime, assuming that the queue logic could generally work with any data source (store). I suggested leaving the prop `onQueueCreated`. 

However, I agree that `createHandleQueueCreated` function could not be exported.

File: src/lib/extension-load-queue.ts [hunk 7]
```diff
@@ -35,21 +35,43 @@ export type ScriptStore<T> = ControllerLoadedCallback<T>[];
...
  * Interface for creating a load queue.
+ *
+ * @template T - Type of the controller created in the queue.
  */
 export interface CreateLoadQueueArgs<T> {
-    // The store where callbacks are saved
+    /**
+     * The store where callbacks are saved.
+     *
+     * @type {ScriptStore<T>}
```
Comment (brotheroftux) [inline src/lib/extension-load-queue.ts:45]: This is a nitpick, but I'd say it makes very little sense to use JSDoc type annotations in presence of TypeScript.

**Review by brotheroftux — APPROVED** [review]
The decision on whether or not to fix the nitpick mentioned is ultimately up to you. Everything else looks good.
